# Generated by Django 4.0.2 on 2022-02-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='name@email.com', max_length=254),
        ),
    ]
